### ISSUE TITLE
Unable to serve the app

### ISSUE THREAD

**Issue by krypton4149** [umun-tech/page#1]
When ever I try to serve the app using `nx serve mobile-app` I get this error

```bash
<e> [webpack-dev-middleware] file:///Users/darkseid/Downloads/umn-page-examples-master/node_modules/@angular/compiler-cli/bundles/chunk-K2Z44JHH.js:12
<e> import { decode, encode } from "sourcemap-codec";
<e>          ^^^^^^
<e> SyntaxError: The requested module 'sourcemap-codec' does not provide an export named 'decode'
<e>     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
<e>     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
<e>     at async Loader.import (internal/modules/esm/loader.js:179:24)
<e>     at async importModuleDynamicallyWrapper (internal/vm/module.js:432:15)
<e>     at async AngularWebpackPlugin.initializeCompilerCli (/Users/darkseid/Downloads/umn-page-examples-master/node_modules/@ngtools/webpack/src/ivy/plugin.js:533:35)
```

**Comment by krypton4149** [comment]
I was able solve this by switching to `node v14.15`.

```bash
nvm install 14.15
nvm use 14.15
```

Install nvm (node version manager) if not already.

Curious thing is i wasn't able to run this using node `20`, `14.18`, `14.19`, `18.15`.
